# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-05 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='article2tag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='article2tag',
            name='article',
        ),
        migrations.RemoveField(
            model_name='article2tag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='articledetail',
            name='article',
        ),
        migrations.AlterUniqueTogether(
            name='articleupdown',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='articleupdown',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleupdown',
            name='user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Article2Tag',
        ),
        migrations.DeleteModel(
            name='ArticleDetail',
        ),
        migrations.DeleteModel(
            name='ArticleUpDown',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
