# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-05 08:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userinfo_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
