# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-06 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190906_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='blog',
        ),
        migrations.AddField(
            model_name='category',
            name='blog',
            field=models.ManyToManyField(to='blog.Blog'),
        ),
    ]
