# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-11 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_userinfo_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='avatar',
            new_name='avatars',
        ),
    ]
