# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-11 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_userinfo_avatars_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatars',
            field=models.FileField(default='/static/default.jpg', upload_to='avatars/', verbose_name='头像'),
        ),
    ]
