# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-11 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190911_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
