# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-11 09:50
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190911_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatars',
            field=models.FileField(default='avatars_default/default.jpg', upload_to=blog.models.user_directory_path, verbose_name='头像'),
        ),
    ]
