# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-11 10:15
from __future__ import unicode_literals

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190911_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11, null=True, unique=True)),
                ('avatars', models.ImageField(default='avatars_default/default.jpg', upload_to=blog.models.user_directory_path, verbose_name='头像')),
                ('avatars_default', models.IntegerField(choices=[(0, '默认头像'), (1, '用户上传头像')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='avatars',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='avatars_default',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='phone',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
