# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-16 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20190911_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='avatars_default',
            new_name='user_avatars',
        ),
    ]
