# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-16 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20190916_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_delete',
            field=models.IntegerField(choices=[(0, '未被删除'), (1, '被删除')], default=0),
        ),
    ]
